FROM openjdk:11
ADD ./target/service-provider-profile-service-0.0.1-SNAPSHOT.jar /usr/src/service-provider-profile-service-0.0.1-SNAPSHOT.jar
WORKDIR usr/src
ENTRYPOINT ["java","-jar","service-provider-profile-service-0.0.1-SNAPSHOT.jar"]





