FROM openjdk:11
ADD ./target/team-management-service-0.0.1-SNAPSHOT.jar /usr/src/team-management-service-0.0.1-SNAPSHOT.jar
WORKDIR usr/src
ENTRYPOINT ["java","-jar","team-management-service-0.0.1-SNAPSHOT.jar"]
